name: Github Action sharing - Deploy  

on:
  push:
    branches:
      - master

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get image tag 
        run: echo "IMAGE_TAG=$(git rev-list --count HEAD)" >> $GITHUB_ENV
      - name: Build image
        run: docker build -t "${{ env.IMAGE_NAME }}" .
      - name: Docker login
        run: echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_ACR_USER }} --password-stdin ${{ env.DOCKER_REGISTRY }}
      - name: Push image latest
        run: |
          docker tag "${{ env.IMAGE_NAME }}" "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}"
          docker push "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}"
      - name: Push image ${{ env.IMAGE_TAG }}
        run: |
          docker tag "${{ env.IMAGE_NAME }}" "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          docker push "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup k8s context 
        run: |
          kubectl config set-cluster aliyun --server=http://${{ secrets.ALIYUN_K8S_USER }}:${{ secrets.ALIYUN_K8S_PASSWORD }}@${{ env.K8S_SERVER }}
          kubectl config set-context aliyun --cluster=aliyun
          kubectl config use-context aliyun
      - name: Apply
        run : |
          kubectl apply -f k8s-deployment.yaml
          kubectl apply -f k8s-service.yaml

env:
  IMAGE_NAME: service-greeting-jonathan
  IMAGE_NAMESPACE: wdcdavyc
  DOCKER_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  K8S_SERVER: 121.41.43.46:8080
